name-template: "v$RESOLVED_VERSION (not yet released)"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "✨ Features and Enhancements"
    labels:
      - "enhancement"
      - "cli"
  - title: "⚡️ Performance"
    labels:
      - "performance"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
      - "compiler issue"
      - "small fix"
  - title: "📝 Documentation"
    labels:
      - "documentation"
  - title: "✅ Testing"
    labels:
      - "test"
  - title: "👷 CI"
    labels:
      - "github_actions"
  - title: "⬆️ Dependencies"
    collapse-after: 5
    labels:
      - "dependencies"
      - "submodules"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
autolabeler:
  - label: "dependencies"
    title:
      - "/update pre-commit hooks/i"
footer: |
  Many thanks to all contributors!

template: |
  ## 👀 What's Changed

  $CHANGES
