name: 🔖 • Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    name: Draft Release

    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
