name: Ubuntu CI

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.cmake'
      - '**/CMakeLists.txt'
      - 'libs/**'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.cmake'
      - '**/CMakeLists.txt'
      - 'libs/**'
      - '.github/workflows/ubuntu.yml'

defaults:
  run:
    shell: bash


jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
        #compiler: [ g++-9, g++-10, clang++-10, clang++-11, clang++-12 ]
        compiler: [ clang++-12 ]
        build_type: [ Debug, Release ]
        exclude:
          - os: ubuntu-22.04
            compiler: clang++-10
        include:
          - os: ubuntu-20.04
            compiler: g++-10
            build_type: Release
            cppstandard: -DQUICKSIM-SIQAD-PLUGIN_CXX_STANDARD=20
            cppname: C++20

    name: ${{matrix.os}} with ${{matrix.compiler}} (${{matrix.build_type}} mode) ${{matrix.cppname}}
    runs-on: ${{matrix.os}}

    steps:
      - name: Install libraries and the respective compiler
        run: sudo apt-get update && sudo apt-get install -yq libtbb-dev ${{matrix.compiler}}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'

      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive


      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: >
          cmake ${{github.workspace}} ${{matrix.cppstandard}}
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
          -DQUICKSIM_TEST=ON

      - name: Build quicksim-siqad-plugin
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{matrix.build_type}} --verbose
